postgres:
  connection_string: 'host=/var/run/postgresql port=5432 user=vladimmi password=v1adimm1'

services:
  annotations:
    class: Doctrine\Common\Annotations\AnnotationReader

  orm_metadata:
    class: Rook\ORM\Metadata\Container

  orm_hydrator:
    class: Rook\ORM\Hydrator
    calls:
      setAnnotations: ['@annotations']
      setMetadataContainer: ['@orm_metadata']

  orm_connection:
    class: Rook\ORM\Connection\Postgres
    construct: ['%postgres']

  repository_character:
    class: Rook\Repository\Character
    calls:
      setConnection: ['@orm_connection']
      setMetadataContainer: ['@orm_metadata']
      setHydrator: ['@orm_hydrator']
      setAnnotations: ['@annotations']